# Generated by Django 2.2.6 on 2019-11-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formname',
            name='verify_email',
        ),
    ]
